### ISSUE TITLE
file doc/db.sql uses wrong database

### ISSUE THREAD

**Issue by cfranz** [kkretsch/lggr#4]
Your Howto on https://lggr.io/howto/ uses database "logger", but the SQL-Export uses "lggrdev" in line 16/17.

```
CREATE DATABASE IF NOT EXISTS `lggrdev` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `lggrdev`;
```

**Comment by kkretsch** [comment]
Well spotted, I will submit a changed package in the next days.

**Comment by cfranz** [comment]
Thank you
